### ISSUE TITLE
Clarify the proxy mode

### ISSUE THREAD

**Issue by toxic0berliner** [lhw/cloudweatherproxy#26]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/cloudweatherproxy/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I did setup the integration.
I believe that it will accept both WeatherUnderground and WeatherCloud and display them in home-assistant regardless of the "proxy" checkbox during the setup, but I might be wrong.

If not the case, please disregard the proposed solution below, more clarification is required maybe elsewhere :D

### Describe the solution you'd like

Clarify on the setup screen that "proxy WU" or "proxy WC" simply enables the forwarding to the cloud of the recieved metrics, leaving it unchecked will still display the values in HA

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by lhw** [comment]
Thats actually a fair point. I wanted to introduce some changes to the configflow anyway. Reconfiguration was part of that. I'll try to make it more readable and precise.
